"""Standard material templates for HiStrA bridge finite element models."""
from __future__ import annotations

from typing import Any, Dict

# Standard masonry template 18 for arch rings and superstructure
MASONRY_18: Dict[str, str] = {
    "TypeOf": "HiStrA.Objects.MasonryMaterial",
    "idCategoria": "1",
    "ValueSetting": "Med",
    "ValueSettingStrength": "Med",
    "IsExistent": "true",
    "SimpleMode": "false",
    "IsDuctCompr": "false",
    "IsDuctTraz": "true",
    "LC_": "LC2",
    "existentMasonryMaterial": "MuraturaMattoniPieniNTC18",
    "E_min": "120",
    "E_med": "150",
    "E_max": "180",
    "G_min": "40",
    "G_med": "50",
    "G_max": "60",
    "Gd": "704",
    "fm_min": "0.26",
    "fm_med": "0.36",
    "fm_max": "0.46",
    "fmd": "0.24",
    "fvk0_min": "0.005",
    "fvk0_med": "0.009",
    "fvk0_max": "0.013",
    "fvk0d": "0.029",
    "w": "2.24E-05",
    "Malta": "false",
    "MaltaValue": "-1",
    "Giunti": "false",
    "GiuntiValue": "-1",
    "Ricorsi": "false",
    "RicorsiValue": "-1",
    "Connessioni": "false",
    "ConnessioniValue": "1.3",
    "Nucleo": "false",
    "NucleoValue": "-1",
    "Iniezioni": "false",
    "IniezioniValue": "1.2",
    "Intonaco": "false",
    "IntonacoValue": "1.5",
    "Diatoni": "false",
    "DiatoniValue": "-1",
    "Ristilatura": "false",
    "RistilaturaValue": "1.2",
    "classe": "classeM2",
    "composizioneClasse": "IdraulicaM2",
    "classeEsecuzione": "Prima",
    "gammam": "2",
    "prestazioneocomposizione": "false",
    "fmdichiarata": "25",
    "nnlinpf": "true",
    "ConstitutiveLawFlex": "ElastoPlasticDuctilityFixed",
    "TensileCurveType": "LinearSoftening",
    "CompressiveCurveType": "LinearSoftening",
    "TensileCurveTypeVertical": "LinearSoftening",
    "CompressiveCurveTypeVertical": "LinearSoftening",
    "Gt": "0.0002",
    "GtVer": "0.0002",
    "Gc": "0.03",
    "GcVer": "0.03",
    "ortpf": "false",
    "Ehor": "1620",
    "Ever": "1620",
    "RatioEtTraction": "0.0001",
    "RatioEtTractionVer": "0.0001",
    "RatioEtCompression": "0.0001",
    "RatioEtCompressionVer": "0.0001",
    "FmHor": "2.68",
    "FmVer": "2.68",
    "FtmHor": "0.02",
    "FtmVer": "0.02",
    "RotationLimitRockingHor": "0.6",
    "RotationLimitRockingVer": "0.6",
    "DuctTrazRockingHor": "1.5",
    "DuctTrazRockingVer": "1.5",
    "DuctComprRockingVer": "1.5",
    "DuctComprRockingHor": "1.5",
    "UnloadTractionRockingHor": "Origin",
    "BetaUnloadTractionRockingHor": "1",
    "UnloadTractionRockingVer": "Origin",
    "BetaUnloadTractionRockingVer": "1",
    "UnloadCompressionRockingHor": "Initial",
    "BetaUnloadCompressionRockingHor": "0",
    "UnloadCompressionRockingVer": "Initial",
    "BetaUnloadCompressionRockingVer": "0",
    "CriterioSnervamento": "Coulomb",
    "ConstitutiveLawMasonryShear": "ElastoPlasticDuctilityFixed",
    "orttagl": "false",
    "DuctilityShear": "100",
    "FrictionRatioShear": "0.5",
    "FractureEnergyShear": "0.5",
    "HasKinCiclShear": "false",
    "AkinCiclShear": "-1",
    "CiclShear": "false",
    "AlfaCiclShear": "-1",
    "GammaCiclShear": "1",
    "UnloadShear": "Initial",
    "BetaUnloadShear": "0",
    "ShearMaxTensileRatio": "0.5",
    "ShearReloadStiffnessRatio": "1",
    "ShearPlasticStiffnessRatio": "0",
    "ShearPlasticStiffnessRatio2": "-1",
    "ShearPlasticStrain": "100",
    "ortsc": "false",
    "scorrhor": "true",
    "scorrvert": "true",
    "scorrDir3": "true",
    "FlexuralOrthotropyType": "false",
    "SlidingYieldingDomainHor": "Coulomb",
    "SlidingYieldingDomainVert": "Coulomb",
    "SlidingYieldingDomainDir3": "Coulomb",
    "CohesionSlidingHor": "0.029",
    "CohesionSlidingVert": "0.029",
    "CohesionSlidingDir3": "0.029",
    "FrictionRatioSlidingHor": "0.5",
    "FrictionRatioSlidingVert": "0.5",
    "FrictionRatioSlidingDir3": "0.5",
    "AlfaShearUser": "0.9",
    "SlidingPlasticStiffnessRatioHor": "0",
    "SlidingPlasticStiffnessRatioVer": "0.001",
    "SlidingPlasticStiffnessRatioDir3": "0.001",
    "SlidingMaxTensileRatioHor": "0.8",
    "SlidingMaxTensileRatioVer": "0.8",
    "SlidingFractureEnergy": "false",
    "SlidingFractureEnergyDir3": "false",
    "SlidingFractureEnergyVer": "false",
    "Gs": "0.02",
    "GsVer": "0.02",
    "GsDir3": "0.02",
    "CheckContactArea": "false",
    "Bcacovic": "1.5",
    "Key": "18",
    "Name": "Masonry",
    "Description": "Muratura in mattoni pieni e malta di calce ",
    "PurposeType": "MasonryMaterial",
    "IdTexture": "1",
    "Color": "#FF3300",
}

# Standard pier cap template 22
PIER_CAP_22: Dict[str, str] = dict(MASONRY_18)
PIER_CAP_22.update({
    "Key": "22",
    "Name": "Pier cap",
    "Gd": "41.7",
    "Color": "#006700",
})

# Standard foundation masonry template 141
FOUNDATION_141: Dict[str, str] = dict(MASONRY_18)
FOUNDATION_141.update({
    "Key": "141",
    "Name": "Foundation",
    "Color": "#FF1978B6",
})

# Standard soil material template 146
SOIL_146: Dict[str, str] = {
    "TypeOf": "HiStrA.Objects.MasonryMaterial",
    "idCategoria": "1",
    "ValueSetting": "Min",
    "ValueSettingStrength": "Min",
    "IsExistent": "true",
    "SimpleMode": "false",
    "IsDuctCompr": "true",
    "IsDuctTraz": "true",
    "LC_": "LC1",
    "existentMasonryMaterial": "MuraturaMattoniPieniNTC08",
    "E_min": "120",
    "E_med": "150",
    "E_max": "180",
    "G_min": "40",
    "G_med": "50",
    "G_max": "60",
    "Gd": "2.08",
    "fm_min": "0.24",
    "fm_med": "0.32",
    "fm_max": "0.4",
    "fmd": "0.1",
    "fvk0_min": "0.006",
    "fvk0_med": "0.0076",
    "fvk0_max": "0.0092",
    "fvk0d": "0.001",
    "w": "2.22E-05",
    "Malta": "false",
    "MaltaValue": "1.5",
    "Giunti": "false",
    "GiuntiValue": "1.5",
    "Ricorsi": "false",
    "RicorsiValue": "-1",
    "Connessioni": "false",
    "ConnessioniValue": "1.3",
    "Nucleo": "true",
    "NucleoValue": "0.7",
    "Iniezioni": "false",
    "IniezioniValue": "1.5",
    "Intonaco": "false",
    "IntonacoValue": "1.5",
    "Diatoni": "false",
    "DiatoniValue": "1.5",
    "Ristilatura": "false",
    "RistilaturaValue": "-1",
    "classe": "classeM2",
    "composizioneClasse": "IdraulicaM2",
    "classeEsecuzione": "Prima",
    "gammam": "2",
    "prestazioneocomposizione": "true",
    "fmdichiarata": "25",
    "nnlinpf": "true",
    "ConstitutiveLawFlex": "ElastoPlasticDuctilityFixed",
    "TensileCurveType": "LinearSoftening",
    "CompressiveCurveType": "LinearSoftening",
    "TensileCurveTypeVertical": "LinearSoftening",
    "CompressiveCurveTypeVertical": "LinearSoftening",
    "Gt": "0.0001",
    "GtVer": "0.0001",
    "Gc": "0.03",
    "GcVer": "0.03",
    "ortpf": "false",
    "Ehor": "5",
    "Ever": "5",
    "RatioEtTraction": "0",
    "RatioEtTractionVer": "0",
    "RatioEtCompression": "0",
    "RatioEtCompressionVer": "0",
    "FmHor": "0.03",
    "FmVer": "0.03",
    "FtmHor": "0.0001",
    "FtmVer": "0.0001",
    "RotationLimitRockingHor": "0.6",
    "RotationLimitRockingVer": "0.6",
    "DuctTrazRockingHor": "1.5",
    "DuctTrazRockingVer": "1.5",
    "DuctComprRockingVer": "1.5",
    "DuctComprRockingHor": "1.5",
    "UnloadTractionRockingHor": "Origin",
    "BetaUnloadTractionRockingHor": "1",
    "UnloadTractionRockingVer": "Origin",
    "BetaUnloadTractionRockingVer": "1",
    "UnloadCompressionRockingHor": "Initial",
    "BetaUnloadCompressionRockingHor": "0",
    "UnloadCompressionRockingVer": "Initial",
    "BetaUnloadCompressionRockingVer": "0",
    "CriterioSnervamento": "Coulomb",
    "ConstitutiveLawMasonryShear": "ElastoPlasticDuctilityFixed",
    "orttagl": "false",
    "DuctilityShear": "100",
    "FrictionRatioShear": "1.427",
    "FractureEnergyShear": "0.5",
    "HasKinCiclShear": "false",
    "AkinCiclShear": "-1",
    "CiclShear": "false",
    "AlfaCiclShear": "-1",
    "GammaCiclShear": "1",
    "UnloadShear": "Initial",
    "BetaUnloadShear": "0",
    "ShearMaxTensileRatio": "0.5",
    "ShearReloadStiffnessRatio": "1",
    "ShearPlasticStiffnessRatio": "0",
    "ShearPlasticStiffnessRatio2": "-1",
    "ShearPlasticStrain": "100",
    "ortsc": "false",
    "scorrhor": "true",
    "scorrvert": "true",
    "scorrDir3": "true",
    "FlexuralOrthotropyType": "false",
    "SlidingYieldingDomainHor": "Coulomb",
    "SlidingYieldingDomainVert": "Coulomb",
    "SlidingYieldingDomainDir3": "Coulomb",
    "CohesionSlidingHor": "0.0001",
    "CohesionSlidingVert": "0.0001",
    "CohesionSlidingDir3": "0.0001",
    "FrictionRatioSlidingHor": "1.427",
    "FrictionRatioSlidingVert": "1.427",
    "FrictionRatioSlidingDir3": "1.427",
    "AlfaShearUser": "0.9",
    "SlidingPlasticStiffnessRatioHor": "0",
    "SlidingPlasticStiffnessRatioVer": "0.001",
    "SlidingPlasticStiffnessRatioDir3": "0.001",
    "SlidingMaxTensileRatioHor": "0.8",
    "SlidingMaxTensileRatioVer": "0.8",
    "SlidingFractureEnergy": "false",
    "SlidingFractureEnergyDir3": "false",
    "Gs": "0.02",
    "SlidingFractureEnergyVer": "false",
    "GsVer": "0.02",
    "GsDir3": "0.02",
    "CheckContactArea": "false",
    "Bcacovic": "1.5",
    "Key": "146",
    "Name": "Soil",
    "Description": "Muratura in mattoni pieni e malta di calce",
    "PurposeType": "MasonryMaterial",
    "IdTexture": "1",
    "Color": "#FFDF3595",
}

# Standard backfill template 19
BACKFILL_19: Dict[str, str] = dict(MASONRY_18)
BACKFILL_19.update({
    "Key": "19",
    "Name": "Backfill",
    "Gd": "2.08",
    "Ehor": "5",
    "Ever": "5",
    "FmHor": "0.09",
    "FmVer": "0.09",
    "FtmHor": "0.0001",
    "FtmVer": "0.0001",
    "FrictionRatioShear": "1.427",
    "Color": "#996633",
})

# Standard scoured soil material template 147 (degraded stiffness and strength)
SOIL_REMOVED_147: Dict[str, str] = dict(SOIL_146)
SOIL_REMOVED_147.update({
    "Key": "147",
    "Name": "Soil_removed",
    "Gd": "0.0208",
    "Ehor": "0.005",
    "Ever": "0.005",
    "FmHor": "0.003",
    "FmVer": "0.003",
    "FtmHor": "1E-05",
    "FtmVer": "1E-05",
    "FrictionRatioShear": "0.01",
    "CohesionSlidingHor": "1E-06",
    "CohesionSlidingVert": "1E-06",
    "CohesionSlidingDir3": "1E-06",
    "FrictionRatioSlidingHor": "0.1",
    "FrictionRatioSlidingVert": "0.1",
    "FrictionRatioSlidingDir3": "0.1",
    "Color": "#FF3DF6EE",
})

DEFAULT_TEMPLATES = [
    MASONRY_18,
    BACKFILL_19,
    PIER_CAP_22,
    FOUNDATION_141,
    SOIL_146,
    SOIL_REMOVED_147,
]
